name: 'biblio'

services:
  web:
    build: .
    volumes:
      - ./:/var/www/html/
    ports:
      - '8000:80'
    depends_on:
      - mailhog

  mariadb:
    image: mariadb:latest
    ports:
      - '3314:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
    volumes:
      - bibliothequedb:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '8001:80'
    environment:
      - PMA_HOST=${MYSQL_HOST}
    depends_on:
      - mariadb

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - '1025:1025' # Port SMTP pour capturer les e-mails
      - '8025:8025' # Port HTTP pour accéder à l'interface Web de MailHog

volumes:
  bibliothequedb:
